/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/brown-building.glb -o src/models/BrownBuilding.tsx -r public -t 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    BrownBuilding_1: THREE.Mesh
    BrownBuilding_2: THREE.Mesh
    BrownBuilding_3: THREE.Mesh
    BrownBuilding_4: THREE.Mesh
    BrownBuilding_5: THREE.Mesh
  }
  materials: {
    brick_shade3: THREE.MeshStandardMaterial
    sandstone: THREE.MeshStandardMaterial
    window_glass: THREE.MeshStandardMaterial
    window_frame: THREE.MeshStandardMaterial
    concrete: THREE.MeshStandardMaterial
  }
}

export function useBrownBuilding() {
  return useGLTF('/models/brown-building.glb') as unknown as GLTFResult
}

export const BROWN_BUILDING_INNER_TRANSFORM = {
  position: [-0.1, 1, -0.383] as [number, number, number],
  rotation: [-Math.PI / 2, 0, 0] as [number, number, number],
  scale: 100,
}

export function Model(props: ThreeElements['group']) {
  const { nodes, materials } = useBrownBuilding()
  return (
    <group {...props} dispose={null}>
      <group {...BROWN_BUILDING_INNER_TRANSFORM}>
        <mesh geometry={nodes.BrownBuilding_1.geometry} material={materials.brick_shade3} />
        <mesh geometry={nodes.BrownBuilding_2.geometry} material={materials.sandstone} />
        <mesh geometry={nodes.BrownBuilding_4.geometry} material={materials.window_frame} />
        <mesh geometry={nodes.BrownBuilding_5.geometry} material={materials.concrete} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/brown-building.glb')
