/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/lamp-post.glb -o src/models/LampPost.tsx -r public -t 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    ['Node-Mesh']: THREE.Mesh
    ['Node-Mesh_1']: THREE.Mesh
    ['Node-Mesh_2']: THREE.Mesh
  }
  materials: {
    lambert4SG: THREE.MeshStandardMaterial
    lambert2SG: THREE.MeshStandardMaterial
    lambert3SG: THREE.MeshStandardMaterial
  }
}

export function Model({
  emissiveMaterial,
  ...props
}: ThreeElements['group'] & { emissiveMaterial?: THREE.Material }) {
  const { nodes, materials } = useGLTF('/models/lamp-post.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Node-Mesh'].geometry} material={materials.lambert4SG} />
      <mesh geometry={nodes['Node-Mesh_1'].geometry} material={emissiveMaterial ?? materials.lambert2SG} />
      <mesh geometry={nodes['Node-Mesh_2'].geometry} material={materials.lambert3SG} />
    </group>
  )
}

useGLTF.preload('/models/lamp-post.glb')
