/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/small-building.glb -o src/models/SmallBuilding.tsx -r public -t 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { type ThreeElements } from '@react-three/fiber'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    small_buildingE_1: THREE.Mesh
    small_buildingE_1_1: THREE.Mesh
    small_buildingE_1_2: THREE.Mesh
    small_buildingE_1_3: THREE.Mesh
    small_buildingE_1_4: THREE.Mesh
  }
  materials: {
    border: THREE.MeshStandardMaterial
    door: THREE.MeshStandardMaterial
    _defaultMat: THREE.MeshStandardMaterial
    window: THREE.MeshStandardMaterial
    roof: THREE.MeshStandardMaterial
  }
}

export function useSmallBuilding() {
  return useGLTF('/models/small-building.glb') as unknown as GLTFResult
}

export function Model(props: ThreeElements['group']) {
  const { nodes, materials } = useSmallBuilding()
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.small_buildingE_1.geometry} material={materials.border} />
      <mesh geometry={nodes.small_buildingE_1_1.geometry} material={materials.door} />
      <mesh geometry={nodes.small_buildingE_1_2.geometry} material={materials._defaultMat} />
      <mesh geometry={nodes.small_buildingE_1_4.geometry} material={materials.roof} />
    </group>
  )
}

useGLTF.preload('/models/small-building.glb')
